version: '3.3'

services:
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
    volumes:
      - ./smtp-data:/smtp4dev

  easycontactforms:
    build: .
    ports:
      - "8080:8080"