@startuml
package org.easycontactforms{
package api {
    [Plugin]
    [PluginFactory]
    [Plugin] --> [PluginFactory]
}

package core {

    package controller {
        [ContactFormController]
    }
    package dtos {
         [ContactFormDto]
         [ErrorDto]
    }
    package models {
         [ContactForm]
    }
    package repositories {
        [ContactFormRepository]
    }

    package services{
        [Mailing-Service]
        [Mailing-Thread]
        [ContactFormService]

        [Mailing-Thread]-->[Mailing-Service]
    }
    [PluginLoader]
    [PluginClassLoader]
    [PluginStore]
    [ApplicationState]
    [ContactFormHandlerApplication]
    [ContactFormHandlerApplication] --> [PluginLoader]
    [ContactFormHandlerApplication] --> [PluginStore]
    [Mailing-Thread] --> [ApplicationState]
    [ContactFormService] --> [ContactFormRepository]

    [ContactFormController] --> [ContactFormService]
    [ContactFormService] --> [Mailing-Thread]
    [ContactFormController] --> [PluginLoader]
    [ContactFormService] --> [PluginLoader]
    [Mailing-Service] --> [PluginLoader]
    [PluginLoader] --> [PluginClassLoader]
    [PluginClassLoader] --> [Plugin]
    [PluginClassLoader] --> [PluginFactory]

}
}
@enduml